# Generated by Django 3.2.9 on 2021-11-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.article')),
                ('who_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.account')),
            ],
        ),
    ]
