# Generated by Django 3.2.9 on 2021-11-20 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20211120_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('com_date', models.DateField(default=datetime.date.today)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.question')),
            ],
        ),
    ]
