# Generated by Django 3.2.9 on 2021-11-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_answer_who_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='com_date',
            new_name='ans_date',
        ),
    ]
