# Generated by Django 3.2.9 on 2021-11-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_rename_com_date_answer_ans_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='opinion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
