# Generated by Django 3.2.9 on 2021-11-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20211129_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vote_score',
        ),
    ]
