# Generated by Django 3.2.9 on 2021-11-30 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20211129_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ans_date', models.DateField(default=datetime.date.today)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.answer')),
                ('who_replay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.account')),
            ],
        ),
    ]
