# Generated by Django 3.2.9 on 2021-12-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_remove_answer_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='who_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='forum.account'),
        ),
        migrations.CreateModel(
            name='Opinon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('which_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.answer')),
                ('who_opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.account')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='opinions',
            field=models.ManyToManyField(related_name='opinion', through='forum.Opinon', to='forum.Account'),
        ),
    ]
