# Generated by Django 3.2.9 on 2021-11-19 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
