# Generated by Django 3.2.9 on 2021-11-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='coding', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='coding', max_length=50),
        ),
    ]
