# Generated by Django 3.2.9 on 2021-11-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20211120_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='who_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.account'),
        ),
    ]
