# Generated by Django 3.2.9 on 2021-11-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replay',
            name='answer',
        ),
        migrations.AddField(
            model_name='replay',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.comment'),
        ),
    ]
