# Generated by Django 3.2.9 on 2021-11-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20211130_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.article'),
        ),
    ]
