# Generated by Django 3.2.9 on 2021-12-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_rename_ans_date_replay_rep_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='opinion',
        ),
    ]
