# Generated by Django 4.0.1 on 2022-01-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Somethink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somethink', models.CharField(max_length=20)),
            ],
        ),
    ]
